//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFillExecutionPublisherService", CallbackContract=typeof(UserInterface.ServiceReference1.IFillExecutionPublisherServiceCallback))]
    public interface IFillExecutionPublisherService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFillExecutionPublisherService/SubscribeToFillExecutions")]
        void SubscribeToFillExecutions(int deskId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFillExecutionPublisherService/SubscribeToFillExecutions")]
        System.Threading.Tasks.Task SubscribeToFillExecutionsAsync(int deskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFillExecutionPublisherServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFillExecutionPublisherService/OnNext")]
        void OnNext(System.Tuple<int, decimal>[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFillExecutionPublisherServiceChannel : UserInterface.ServiceReference1.IFillExecutionPublisherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FillExecutionPublisherServiceClient : System.ServiceModel.DuplexClientBase<UserInterface.ServiceReference1.IFillExecutionPublisherService>, UserInterface.ServiceReference1.IFillExecutionPublisherService {
        
        public FillExecutionPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FillExecutionPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FillExecutionPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FillExecutionPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FillExecutionPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeToFillExecutions(int deskId) {
            base.Channel.SubscribeToFillExecutions(deskId);
        }
        
        public System.Threading.Tasks.Task SubscribeToFillExecutionsAsync(int deskId) {
            return base.Channel.SubscribeToFillExecutionsAsync(deskId);
        }
    }
}
