//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IMarketPlacementPublisherService", CallbackContract=typeof(UserInterface.ServiceReference2.IMarketPlacementPublisherServiceCallback))]
    public interface IMarketPlacementPublisherService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMarketPlacementPublisherService/SubscribeToMarketPlacements")]
        void SubscribeToMarketPlacements(int deskId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMarketPlacementPublisherService/SubscribeToMarketPlacements")]
        System.Threading.Tasks.Task SubscribeToMarketPlacementsAsync(int deskId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketPlacementPublisherServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMarketPlacementPublisherService/OnNext")]
        void OnNext(System.Tuple<System.Tuple<int, int, decimal, decimal>, Notifications.DataChangeType>[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketPlacementPublisherServiceChannel : UserInterface.ServiceReference2.IMarketPlacementPublisherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketPlacementPublisherServiceClient : System.ServiceModel.DuplexClientBase<UserInterface.ServiceReference2.IMarketPlacementPublisherService>, UserInterface.ServiceReference2.IMarketPlacementPublisherService {
        
        public MarketPlacementPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MarketPlacementPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MarketPlacementPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlacementPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MarketPlacementPublisherServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeToMarketPlacements(int deskId) {
            base.Channel.SubscribeToMarketPlacements(deskId);
        }
        
        public System.Threading.Tasks.Task SubscribeToMarketPlacementsAsync(int deskId) {
            return base.Channel.SubscribeToMarketPlacementsAsync(deskId);
        }
    }
}
